# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "http://covid19italia.info"

#baseurl: "https://github.com/emergenzeha/COVID19"
url: "https://covid19italia.help"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Covid19Italia.help

# Logo description
logo-description: Il logo di covid19italia due cerchi concentrici uno rosso e uno verde ed all'esterno dei semicerchi sparsi

# Short description of your site
description: Un progetto per condividere informazioni a supporto dell'emergenza COVID19

# --- Navigation bar options --- #
# List of links in the navigation bar
navbar-links:
  SEGNALA: "segnala/"
  SCOPRI:
    - SEGNALAZIONI : "issues/"
    - SEGNALAZIONI PER REGIONE: "issues/regione/"
  SEGUI:
     - NOTIZIE: "notizie/"
     - BLOG : "post/"
     - CONTATTI: "canali/"
     #- Fake News: "fake-news/"
  # Link Utili:
  #   - Iniziative solidali: "servizi_e_iniziative_solidali/"
  #   - Opendata: "opendata/"
  COS'È?:
   - ABOUT: "about/"
   - PRESS: "press/"
   - DOMANDE FREQUENTI: "faq/"
   - OPEN DATA: "opendata/"
  PARTECIPA!: "contribuisci/"
  PRIVACY: "legal"
  #  - Rilancia informazioni sui social: ''

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/covid19italia.png

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: COVID19Italia
  email: "mailto:covid19ita@gmail.com"
  facebook: covid19italia.help  # eg. daattali
  facebook_group: 2921275147894653
  github: emergenzeHack/covid19italia    # eg. daattali
  twitter: ItaliaCovid19   # eg. daattali
  #linkedin:   # eg. daattali
  #xing:       # eg. daattali
  #stackoverflow:   # eg. "3943160/daattali"
  instagram: covid19italia.help # eg. daattali
  #youtube: yourlink # eg. user/daattali or channel/daattali
  #rss: https://emergenzehack.github.io/covid19italia/feed.xml
  telegram: https://t.me/COVID19I
  #medium: https://medium.com/@covid19italia
  #archiveorg: https://archive.org/details/@covid19italia
  #messenger: messenger
  #telegram_bot: to do
  #androidapp: to do
  #messenger: to do
  telegram_group: https://t.me/COVID19I

# Select which links to show in the footer
footer-links-active:
  androidapp: false
  rss: false
  facebook: true
  email: false
  twitter: true
  github: true
  linkedin: false
  xing: false
  stackoverflow: false
  instagram: true
  youtube: false
  telegram: true
  medium: false
  archiveorg: false
  messenger: false
  waze: false
  flickr: false

# Select which share links to show in posts
share-links-active:
  google: false
  androidapp: false
  rss: false
  facebook: true
  email: true
  twitter: true
  github: true
  linkedin: false
  xing: false
  stackoverflow: false
  instagram: true
  youtube: false
  telegram: true
  medium: false
  archiveorg: false
  messenger: false
  waze: false
  flickr: false
  telegram_bot: false
  telegram_group: true
  rss: true
  link: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
# url-pretty: "MyWebsite.com"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "covid19italia"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-128871385-2"

jekyll-crosseverything_to_medium:
  enabled: false
  useraccount: 'https://medium.com/covid19italia'

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Rome"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5
#selec tile for maps
tile_map: https://a.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png
kramdown:
  input: GFM

jekyll-mentions:
  base_url: https://twitter.com

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags pages (not recommended if you are deploying via GitHub pages, only set to true if deploying locally with ruby)
link-tags: false

include:
  - _data

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile
  - vendor
  - .gitlab-ci.yml

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
    - /scripts
    - /external
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

collections:
  storie:
    output: true
  segnalazioni:
    output: true

gems:
  - jekyll-paginate
  - jekyll-datapage-generator
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-tidy

page_gen-dirs: true # uncomment, if you prefer to generate named folders
page_gen:
    - index_files: false
      data: issuesjson
      template: issue
      name: number
      dir: issues
    - index_files: true
      data: regioni
      template: issuelist_regione
      dir: issues/regione/
      name: nome_regione
    - index_files: true
      data: province.Abruzzo
      template: issuelist_provincia
      dir: issues/regione/abruzzo
      name: nome_provincia
    - index_files: true
      data: province.Basilicata
      template: issuelist_provincia
      dir: issues/regione/basilicata
      name: nome_provincia
    - index_files: true
      data: province.Calabria
      template: issuelist_provincia
      dir: issues/regione/calabria
      name: nome_provincia
    - index_files: true
      data: province.Campania
      template: issuelist_provincia
      dir: issues/regione/campania
      name: nome_provincia
    - index_files: true
      data: province.Emilia-Romagna
      template: issuelist_provincia
      dir: issues/regione/emilia-romagna
      name: nome_provincia
    - index_files: true
      data: province.Friuli Venezia Giulia
      template: issuelist_provincia
      dir: issues/regione/friuli-venezia-giulia
      name: nome_provincia
    - index_files: true
      data: province.Lazio
      template: issuelist_provincia
      dir: issues/regione/lazio
      name: nome_provincia
    - index_files: true
      data: province.Liguria
      template: issuelist_provincia
      dir: issues/regione/liguria
      name: nome_provincia
    - index_files: true
      data: province.Lombardia
      template: issuelist_provincia
      dir: issues/regione/lombardia
      name: nome_provincia
    - index_files: true
      data: province.Marche
      template: issuelist_provincia
      dir: issues/regione/marche
      name: nome_provincia
    - index_files: true
      data: province.Molise
      template: issuelist_provincia
      dir: issues/regione/molise
      name: nome_provincia
    - index_files: true
      data: province.Piemonte
      template: issuelist_provincia
      dir: issues/regione/piemonte
      name: nome_provincia
    - index_files: true
      data: province.Puglia
      template: issuelist_provincia
      dir: issues/regione/puglia
      name: nome_provincia
    - index_files: true
      data: province.Sardegna
      template: issuelist_provincia
      dir: issues/regione/sardegna
      name: nome_provincia
    - index_files: true
      data: province.Sicilia
      template: issuelist_provincia
      dir: issues/regione/sicilia
      name: nome_provincia
    - index_files: true
      data: province.Toscana
      template: issuelist_provincia
      dir: issues/regione/toscana
      name: nome_provincia
    - index_files: true
      data: province.Trentino-Alto Adige
      template: issuelist_provincia
      dir: issues/regione/trentino-alto-adige
      name: nome_provincia
    - index_files: true
      data: province.Umbria
      template: issuelist_provincia
      dir: issues/regione/umbria
      name: nome_provincia
    - index_files: true
      data: province.Valle d'Aosta
      template: issuelist_provincia
      dir: issues/regione/valle-daosta
      name: nome_provincia
    - index_files: true
      data: province.Veneto
      template: issuelist_provincia
      dir: issues/regione/veneto
      name: nome_provincia
      

jekyll_tidy:
  exclude: []
  compress_html: true

categorieissue:
 - Raccolte fondi;Raccolte fondi
 - Giochi/intrattenimento bambini;Giochi/intrattenimento bambini
 - Servizi e iniziative solidali;Servizi e iniziative solidali
 - Iniziative culturali e ricreative;Attivita culturali e ricreative
 - Consegne e commissioni;Consegne e commissioni
 - Supporto psicologico;Supporto psicologico
 - Sostegno lavoro e imprese;Sostegno lavoro e imprese
 - Donazioni beni/strumenti;Donazioni beni/strumenti
 - Didattica a distanza e-learning;Didattica a distanza e-learning
 - Notizie;Notizie

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
